### ISSUE TITLE
ModuleNotFoundError in ISS.algorithms.planning when running roslaunch carla_bridge carla_demo.launch

### ISSUE THREAD

**Issue by Jumbo-zczlbj0** [CAS-LRJ/ISS#26]
## Environment
- Operating System: Docker: nvidia/cuda:11.8.0-devel-ubuntu20.04 image, Ubuntu 20.04, ROS Noetic
- Python Version: Python 3.8.10
- Relevant Package Versions: Carla: 0.9.13

## Description
Encountered a `ModuleNotFoundError` when trying to run `roslaunch carla_bridge carla_demo.launch` in the ros1-dev-reframe. The error suggests that the module `ISS.algorithms.planning` cannot be found or imported.

## Steps to Reproduce
1. Run `roslaunch carla_bridge carla_demo.launch` from the ISS/ros1_ws/src/carla_bridge/launch directory.
2. Error occurs during the execution.

## Expected Behavior
The script should successfully import all required modules and execute without errors.

## Actual Behavior
The script fails to execute and throws the following error:

Traceback (most recent call last):
File "/container/documents/ISS/ros1_ws/devel/lib/iss_manager/planning_manager_node.py", line 15, in <module>
exec(compile(fh.read(), python_script, 'exec'), context)
File "/container/documents/ISS/ros1_ws/src/iss_manager/scripts/planning_manager_node.py", line 13, in <module>
from ISS.algorithms.planning.global_planner.lanelet2_planner import Lanelet2Planner
ModuleNotFoundError: No module named 'ISS.algorithms.planning'

![2](https://github.com/CAS-LRJ/ISS/assets/124547146/f49ac548-831c-45cd-9029-2b5a27896655)

When trying to manually import the module in Python 3.8.10, the same error occurs:

import ISS
import ISS.algorithms
import ISS.algorithms.planning
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ISS.algorithms.planning'

![5](https://github.com/CAS-LRJ/ISS/assets/124547146/afcca8e2-4bef-46ca-848e-d8d0874b7426)

**Comment by SailorBrandon** [comment]
Please refer to the new commit 902b592d2e053a71b8ed1fb29683af05cdbcc366
