### ISSUE TITLE
Issue with ROS Node Initialization in ros1_dev_reframe Branch

### ISSUE THREAD

**Issue by Jumbo-zczlbj0** [CAS-LRJ/ISS#27]
Description
I encountered an issue while running the roslaunch carla_bridge carla_demo.launch in the ros1_dev_reframe branch. The ROS node related to the control manager for ego_vehicle seems to be initializing and then shutting down unexpectedly.

Environment
ROS Version: noetic
Operating System:  Docker: nvidia/cuda:11.8.0-devel-ubuntu20.04 image, Ubuntu 20.04
Branch: ros1_dev_reframe
Steps to Reproduce
Checkout to ros1_dev_reframe branch.
Run the command: roslaunch carla_bridge carla_demo.launch.
Expected Behavior
The ROS node for the ego vehicle's control manager should initialize and maintain a stable connection with the master node.

Actual Behavior
The node initializes but then shuts down unexpectedly. Here are the relevant logs:

Additional Information
The issue appears to be related to the ego_vehicle/control_manager_node.
No changes were made to the configurations before running the launch file.
[Any other relevant information or logs]
The node initializes but then shuts down unexpectedly. Here are the relevant logs (ego_vehicle-control_manager_node-3.log):

[rospy.client][INFO] 2024-01-09 12:09:57,264: init_node, name[/ego_vehicle/control_manager_node], pid[23964]
[xmlrpc][INFO] 2024-01-09 12:09:57,264: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2024-01-09 12:09:57,265: Started XML-RPC server [http://jumbo-Legion-7-16ITHg6:36747/]
[rospy.init][INFO] 2024-01-09 12:09:57,265: ROS Slave URI: [http://jumbo-Legion-7-16ITHg6:36747/]
[rospy.impl.masterslave][INFO] 2024-01-09 12:09:57,265: _ready: http://jumbo-Legion-7-16ITHg6:36747/
[rospy.registration][INFO] 2024-01-09 12:09:57,265: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2024-01-09 12:09:57,265: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2024-01-09 12:09:57,365: registered with master
[rospy.rosout][INFO] 2024-01-09 12:09:57,365: initializing /rosout core topic
[rospy.rosout][INFO] 2024-01-09 12:09:57,367: connected to core topic /rosout
[rospy.simtime][INFO] 2024-01-09 12:09:57,368: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2024-01-09 12:09:57,376: topic[/ego_vehicle/ego_state_estimation] adding connection to [http://jumbo-Legion-7-16ITHg6:33637/], count 0
[rospy.core][INFO] 2024-01-09 12:09:57,411: signal_shutdown [atexit]
[rospy.internal][INFO] 2024-01-09 12:09:57,413: topic[/ego_vehicle/ego_state_estimation] removing connection to http://jumbo-Legion-7-16ITHg6:33637/
[rospy.impl.masterslave][INFO] 2024-01-09 12:09:57,413: atexit
[rospy.client][INFO] 2024-01-09 12:11:22,211: init_node, name[/ego_vehicle/control_manager_node], pid[24142]
[xmlrpc][INFO] 2024-01-09 12:11:22,212: XML-RPC server binding to 0.0.0.0:0

[xmlrpc][INFO] 2024-01-09 12:11:22,212: Started XML-RPC server [http://jumbo-Legion-7-16ITHg6:38683/]
[rospy.init][INFO] 2024-01-09 12:11:22,212: ROS Slave URI: [http://jumbo-Legion-7-16ITHg6:38683/]
[rospy.impl.masterslave][INFO] 2024-01-09 12:11:22,212: _ready: http://jumbo-Legion-7-16ITHg6:38683/
[rospy.registration][INFO] 2024-01-09 12:11:22,213: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2024-01-09 12:11:22,213: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2024-01-09 12:11:22,312: registered with master
[rospy.rosout][INFO] 2024-01-09 12:11:22,313: initializing /rosout core topic
[rospy.rosout][INFO] 2024-01-09 12:11:22,315: connected to core topic /rosout
[rospy.simtime][INFO] 2024-01-09 12:11:22,316: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.core][INFO] 2024-01-09 12:11:22,359: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2024-01-09 12:11:22,360: atexit

**Comment by SailorBrandon** [comment]
Please refer to the new commit 902b592d2e053a71b8ed1fb29683af05cdbcc366
