### ISSUE TITLE
ModuleNotFoundError and TypeError in ROS Nodes Body:

### ISSUE THREAD

**Issue by Jumbo-zczlbj0** [CAS-LRJ/ISS#28]
Environment:

ROS Version:  ROS Noetic]
Operating System: Docker Ubuntu 20.04
Python Version: Python 3.8.10

Issue Description:
Encountered errors when running ROS nodes related to control_manager_node.py and planning_manager_node.py. The errors seem to relate to missing Python modules and unexpected arguments in class initialization.

Error 1: ModuleNotFoundError

![1](https://github.com/CAS-LRJ/ISS/assets/124547146/5563f6d6-af6a-493f-8ea1-7baa7da8940c)

The ModuleNotFoundError suggests that the module ISS.algorithms.planning.local_planner is missing or not found.

Error 2: TypeError in VehiclePIDController Initialization

![22](https://github.com/CAS-LRJ/ISS/assets/124547146/63d03cfb-65d0-4041-bdf4-d74211e8f49c)

![33](https://github.com/CAS-LRJ/ISS/assets/124547146/6c318c38-33c9-4683-8870-7f744f767cdd)

This error occurs when initializing the VehiclePIDController class, indicating an unexpected keyword argument 'Kp'.

Steps to Reproduce:

Run the control_manager_node.py.
Run the planning_manager_node.py.
Observe the errors in the console.
Expected Behavior:
The nodes should initialize without errors and begin their respective processes.

Actual Behavior:
The nodes fail to initialize due to the mentioned errors.

**Comment by SailorBrandon** [comment]
Please refer to the new commit 902b592d2e053a71b8ed1fb29683af05cdbcc366

**Comment by Jumbo-zczlbj0** [comment]
> Please refer to the new commit [902b592](https://github.com/CAS-LRJ/ISS/commit/902b592d2e053a71b8ed1fb29683af05cdbcc366)

![1](https://github.com/CAS-LRJ/ISS/assets/124547146/c99b0ecc-3aa4-4a77-a92f-627d39549369)
![2](https://github.com/CAS-LRJ/ISS/assets/124547146/bd8f2aca-531e-4101-8e4a-082318981c21)

**Comment by SailorBrandon** [comment]
Did you pull the new commit?

**Comment by Jumbo-zczlbj0** [comment]
> Did you pull the new commit?

Hello,

Regarding the issue, a possible solution is to add an __init__.py file in the /ISS/ISS/algorithms/planning/local_planner directory. This file can be empty, but its presence will help Python recognize the directory as an importable module.

Here are the steps to follow:

Navigate to the /ISS/ISS/algorithms/planning/local_planner directory.
Create an empty __init__.py file.
Return to the ISS folder.
Re-run the python3 setup.py install command.
This should resolve the issue you're encountering. If you continue to 

There is no such file in the original folder:

![1](https://github.com/CAS-LRJ/ISS/assets/124547146/32b2ce63-356c-4ad6-be1e-7d966485a44c)


Best regards!
